### ISSUE TITLE
Duplicates in Server Pagination Grid

### ISSUE THREAD

**Issue by MajedFakhrEldin** [sensor-network/open-data-portal#89]
Environment: The current production version deployed on the server.
Description: The server pagination grid component is showing a lot of duplicates. Take for example location Långö Beach
![Capture](https://user-images.githubusercontent.com/61232033/166895032-58f437d8-a53c-4721-8603-5863531f8d6a.PNG)

Once you scroll down a bit, this will begin to appear. And what's weird is that after scrolling down, seeing the duplicates, once you scroll up, the rows for Pottholmen are replaced by the duplicates of Långö Beach. To confirm that there are no duplicates in the database, you can take a look at http://SERVER_ADDRESS/api/v3/measurements?locationName=L%C3%A5ng%C3%B6+Beach&endTime=2022-05-05&startTime=2022-01-01&temperatureUnit=c&conductivityUnit=spm.
Only two rows exist for location Långö Beach.

**Comment by andreas-bauer** [comment]
@MajedFakhrEldin I removed the actual server address from your issue description.

**Comment by juliusmarminge** [comment]
Have you looked into this any further @MajedFakhrEldin ? I uploaded some more data to reproduce it. (Now present at Page 2)
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/51714798/166978399-5bbe9b1f-8edc-4204-971f-ffafb10810f1.png">

**Comment by MajedFakhrEldin** [comment]
The only new thing that I seem to notice is that when I sort the grid page by the time or Location Name column, the issue doesn't seem to appear.

**Comment by MajedFakhrEldin** [comment]
I tried reproducing it on my local machine as well, and I cannot get it to appear there.

**Comment by juliusmarminge** [comment]
I think the issue was with how we determined the id's for the rows. Previously we had
```js
getRowId={(row) => row.time}
```
which is not always unique, there can be multiple measurements with the same time coming from different locations. I could also reproduce the issue locally if providing rows with the same time.

I modified the id-getter to
```ts
getRowId={(row) =>
  new Date(row.time).getTime() *
  row.position.lat *
  row.position.long
}
```
which should be unique. will try in prod once the image is updated

**Comment by andreas-bauer** [comment]
Is there a way to use the index as ID? In Vue it would be something like `(obj, index) in list`

**Comment by juliusmarminge** [comment]
I believe this is solved. Please verify @MajedFakhrEldin before closing.

**Comment by MajedFakhrEldin** [comment]
I believe so as well.
