### ISSUE TITLE
Summary view not handling nulled data correctly

### ISSUE THREAD

**Issue by juliusmarminge** [sensor-network/open-data-portal#91]
**Describe the bug**
The table is miss-aligned when data for a specific sensor is not present in the latest response. In this example, only a temperature sensor is present causing the conductivity and ph to be miss-aligned.

**To Reproduce**
1. Go to `http://SERVER_ADDRESS/data`
2. Scroll down to `Summarize data over a period`
3. Select `this year` in the date-range-selector.

**Expected behavior**
The table to be properly formatted. If it should display `No data`, or select the latest available for that particular sensor I am not sure. In the case of displaying `No data`, the `Change`-column would also need to be adjusted.

**Screenshots / Snippets**
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/51714798/166914842-87056b22-71d9-45a7-8ed0-7c530ddc0ce2.png">

**Environment**
- Browser: Safari, Chrome

**Comment by andreas-bauer** [comment]
@juliusmarminge I replaced the actual server address with a generic `SERVER_ADDRESS` because of security concerns.

**Comment by juliusmarminge** [comment]
@andreas-bauer What do you think the behavior should be like if there is no data for the period's end (As described in the `Expected behavior` section)?

**Comment by MajedFakhrEldin** [comment]
This issue also happens for the visualized graph on http://SERVER_ADDRESS/data.
![graph](https://user-images.githubusercontent.com/61232033/167258001-29605923-5bcb-4e9a-a27b-fb3ed072859f.PNG)

**Comment by juliusmarminge** [comment]
> This issue also happens for the visualized graph on http://SERVER_ADDRESS/data.
> ![graph](https://user-images.githubusercontent.com/61232033/167258001-29605923-5bcb-4e9a-a27b-fb3ed072859f.PNG)

These issues are not related. The visualization is working as intended. The response from the API is sending back some values as 0 (or -273.15 C). This is reported in #95.

**Comment by juliusmarminge** [comment]
Closing this issue as the original problem is solved. The component is now properly handling the case when there is no data to be displayed. Issue #95 is following up the incorrect data.
